#Database
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: user_email
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: postgres

#SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: test