#Database
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: user_email
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: postgres

#SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ADDRESS: <YOUR EMAIL ADDRESS>
EMAIL_PASSWORD: <YOUR EMAIL PASSWORD
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
